import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: [{ name: "Muhammad Ali", url: "https://github.com/ali-muhammed" }],
  icons: {
    icon: "/icon.png",
  },
  openGraph: {
    title: "home - lele",
  },
};

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1>Hello World </h1>
    </main>
  );
}
